// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VouDeVan.Infrastructure.Database;

namespace VouDeVan.Infrastructure.Database.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VouDeVan.Infrastructure.Database.TransportationCompanies.TransportationCompanyDataRow",
                b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .HasMaxLength(400);

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("FantasyName")
                        .HasMaxLength(50);

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<string>("RepresentativeName")
                        .HasMaxLength(100);

                    b.Property<string>("RepresentativePhone")
                        .HasMaxLength(11);

                    b.Property<string>("SocialName")
                        .HasMaxLength(100);

                    b.Property<string>("Status")
                        .HasMaxLength(40);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate();

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("TransportationCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}